project:
  type: website

website:
  page-navigation: true
  title: "Dendrochronology and R"
  site-url: "https://ronaldvisser.github.io/Dendro_R/"
  repo-url: https://github.com/RonaldVisser/Dendro_R
  repo-actions: [issue]
  google-analytics: G-LLXF7RMDPD
  cookie-consent: TRUE
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-By-NC Ronald Visser, 2024"

  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: R-packages for dendrochronology
      - href: shiny.qmd
        text: Shiny apps
      - href: scripts.qmd
        text: Useful R-scripts for dendrochronology
      - href: about.qmd
        text: About this website
    right:
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/RonaldVisser/Dendro_R
          - text: Report a Bug
            url: https://github.com/RonaldVisser/Dendro_R/issues
      - icon: mastodon
        href: https://akademienl.social/@RonaldVisser

format:
  html:
    theme: spacelab
    code-copy: true
    code-overflow: wrap
    toc: false


filters:
  - quarto

